[package]
name = "slint-timezone-viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.7.2"
chrono = "0.4"

[build-dependencies]
slint-build = "1.7.2"

